version: '3.7'
services:
  php-upstream:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - ./:/data/application:delegated
      - ~/.composer:/root/.composer
    working_dir: /data/application

  nginx:
    image: nginx
    depends_on:
      - php-upstream
    ports:
      - '8080:80'
    links:
      - php-upstream
    volumes:
      - ./public:/data/application/public:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
