services:
  DND\Infrastructure\User\UserPersister:
    class: DND\Infrastructure\User\UserPersister
    arguments:
      - '@doctrine.orm.entity_manager'

  DND\Infrastructure\ItemCard\ItemCardPersister:
    class: DND\Infrastructure\ItemCard\ItemCardPersister
    arguments:
      - '@doctrine.orm.entity_manager'
