services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/Kernel.php'
            - '../src/App/Twig/'

    DND\:
        resource: '../src/DND/'

imports:
    - { resource: 'parameters.yaml' }
