services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\:
        resource: '../src/Service'
        public: true

    App\Calculator\:
        resource: '../src/Calculator'
        public: true

    App\Repository\:
        resource: '../src/Repository'
        public: true

    App\Builder\:
        resource: '../src/Builder'
        public: true

    App\Mapper\:
        resource: '../src/Mapper'
        public: true

    App\Cli\:
        resource: '../src/Cli'
        public: true

    App\Command\WriteFileCommand:
        arguments:
            $itemCardImagesAllowedMime: '%item_card_images_allowed_mime%'
            $itemCardImagesDirectory: '%item_card_images_directory%'

    App\ItemCard\Query\GetItemCardFrontHtmlHandler:
        arguments:
            $itemCardStylesPath: '%item_card_css_path%'

    App\ItemCard\Query\GetItemCardBackHtmlHandler:
        arguments:
            $itemCardStylesPath: '%item_card_css_path%'

    App\ItemCard\Command\UpdateItemCardHandler:
        arguments:
            $itemCardImagesDirectory: '%item_card_images_directory%'

    App\Command\DeleteFileCommand:
        arguments:
            $filesDirectory: '%item_card_images_directory%'

    App\Twig\ProficiencyDot:
        class: App\Twig\ProficiencyDot
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\QuillDeltaParser:
        class: App\Twig\QuillDeltaParser
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\ValueDecorator:
        class: App\Twig\ValueDecorator
        tags: [ 'twig.extension' ]

    App\Twig\UcWords:
        class: App\Twig\UcWords
        tags: [ 'twig.extension' ]

    App\Twig\BackgroundColorCss:
        class: App\Twig\BackgroundColorCss
        arguments:
            - '%character_card_dev_mode%'
        tags: [ 'twig.extension' ]

    App\Twig\GetImageUrl:
        class: App\Twig\GetImageUrl
        arguments:
            - '%item_card_images_directory%'
        tags: [ 'twig.extension' ]

imports:
    - { resource: 'parameters.yaml' }
