services:
  app.command.create_character_card_command:
    class: App\Command\CreateCharacterCardCommand
    arguments:
      - '@DND\CharacterCard\CharacterCardBuilder'
    tags: ['console.command']
