services:
  app.command.create_character_card_command:
    class: App\Command\CreateCharacterCardCommand
    arguments:
      - '@DND\Domain\CharacterCard\CharacterCardBuilder'
    tags: ['console.command']

  App\Command\ImportSQL:
    class: App\Command\ImportSQL
    arguments:
      - '@doctrine.orm.entity_manager'
    tags: [ 'console.command' ]
