services:
  DND\Domain\Command\RegisterUserHandler:
    class: DND\Domain\Command\RegisterUserHandler
    arguments:
      - '@security.user_password_hasher'
      - '@DND\Domain\User\UserPersister'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\RegisterUser, bus: command }

  DND\Domain\Command\ActivateUserHandler:
    class: DND\Domain\Command\ActivateUserHandler
    arguments:
      - '@DND\Domain\User\UserRepository'
      - '@DND\Domain\User\UserPersister'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\ActivateUser, bus: command }

  DND\Domain\Command\DeactivateUserHandler:
    class: DND\Domain\Command\DeactivateUserHandler
    arguments:
      - '@DND\Domain\User\UserRepository'
      - '@DND\Domain\User\UserPersister'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\DeactivateUser, bus: command }

  DND\Domain\Command\DeleteUserHandler:
    class: DND\Domain\Command\DeleteUserHandler
    arguments:
      - '@DND\Domain\User\UserRepository'
      - '@DND\Domain\User\UserPersister'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\DeleteUser, bus: command }

  DND\Domain\Command\CreateItemCardHandler:
    class: DND\Domain\Command\CreateItemCardHandler
    arguments:
      - '@DND\Domain\ItemCard\ItemCardPersister'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\CreateItemCard, bus: command }

  DND\Domain\Command\UpdateItemCardHandler:
    class: DND\Domain\Command\UpdateItemCardHandler
    arguments:
      - '@DND\Domain\ItemCard\ItemCardPersister'
      - '%item_card_images_directory%'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\UpdateItemCard, bus: command }

  DND\Domain\Command\UploadFileHandler:
    class: DND\Domain\Command\UploadFileHandler
    arguments:
      - '@slugger'
      - '%item_card_images_allowed_mime%'
      - '%item_card_images_directory%'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\UploadFile, bus: command }

  DND\Domain\Command\DeleteItemCardHandler:
    class: DND\Domain\Command\DeleteItemCardHandler
    arguments:
      - '@DND\Domain\ItemCard\ItemCardRepository'
      - '@DND\Domain\ItemCard\ItemCardPersister'
      - '%item_card_images_directory%'
    tags:
      - { name: tactician.handler, command: DND\Domain\Command\DeleteItemCard, bus: command }

  Calendar\Domain\Command\GetDatesForCalendarHandler:
    class: Calendar\Domain\Command\GetDatesForCalendarHandler
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Command\GetDatesForCalendar, bus: command }

  Calendar\Domain\Command\GetDatesForCalendarAnswerHandler:
    class: Calendar\Domain\Command\GetDatesForCalendarAnswerHandler
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Command\GetDatesForCalendarAnswer, bus: command }

  Calendar\Domain\Command\CreateCalendarHandler:
    class: Calendar\Domain\Command\CreateCalendarHandler
    arguments:
      - '@Calendar\Domain\Calendar\CalendarPersister'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Command\CreateCalendar, bus: command }

  Calendar\Domain\Command\DeleteCalendarHandler:
    class: Calendar\Domain\Command\DeleteCalendarHandler
    arguments:
      - '@Calendar\Domain\Calendar\CalendarPersister'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Command\DeleteCalendar, bus: command }

  Calendar\Domain\Command\CreateCalendarParticipantsHandler:
    class: Calendar\Domain\Command\CreateCalendarParticipantsHandler
    arguments:
      - '@Calendar\Domain\CalendarParticipant\CalendarParticipantPersister'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Command\CreateCalendarParticipants, bus: command }

  Calendar\Domain\Command\UpdateCalendarParticipantResponseHandler:
    class: Calendar\Domain\Command\UpdateCalendarParticipantResponseHandler
    arguments:
      - '@Calendar\Domain\CalendarParticipant\CalendarParticipantRepository'
      - '@Calendar\Domain\CalendarParticipant\CalendarParticipantPersister'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Command\UpdateCalendarParticipantResponse, bus: command }
