services:
  App\Controller\IndexController:
    class: App\Controller\IndexController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ]]
    tags: [ 'controller.service_arguments' ]

  App\Controller\LoginController:
    class: App\Controller\LoginController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

  App\Controller\RegistrationController:
    class: App\Controller\RegistrationController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\AdminController:
    class: App\Controller\AdminController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\CardController:
    class: App\Controller\CardController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]

  App\Controller\ItemCardController:
    class: App\Controller\ItemCardController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

  App\Controller\CharacterController:
    class: App\Controller\CharacterController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]