services:
  App\Controller\IndexController:
    class: App\Controller\IndexController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [setContainer, [ '@service_container' ]]
    tags: [ 'controller.service_arguments' ]

  App\Controller\CardController:
    class: App\Controller\CardController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: [ 'controller.service_arguments' ]
