services:
  App\Form\DataTransformer\CalendarFormDataTransformer:
    class: App\Form\DataTransformer\CalendarFormDataTransformer
    arguments:
      - '@DND\Domain\User\UserRepository'

  App\Form\CalendarForm:
    class: App\Form\CalendarForm
    arguments:
      - '@App\Form\DataTransformer\CalendarFormDataTransformer'
    tags: [ 'form.type' ]
