services:
  App\Form\DataTransformer\CalendarFormDataTransformer:
    class: App\Form\DataTransformer\CalendarFormDataTransformer
    arguments:
      - '@DND\Domain\User\UserRepository'

  App\Form\DataTransformer\CreateCalendarFormDataTransformer:
    class: App\Form\DataTransformer\CreateCalendarFormDataTransformer
    arguments:
      - '@DND\Domain\User\UserRepository'

  App\Form\CreateCalendarForm:
    class: App\Form\CreateCalendarForm
    arguments:
      - '@App\Form\DataTransformer\CreateCalendarFormDataTransformer'
    tags: [ 'form.type' ]
