services:
  DND\Domain\Query\GetUsersHandler:
    class: DND\Domain\Query\GetUsersHandler
    arguments:
      - '@DND\Domain\User\UserRepository'
    tags:
      - { name: tactician.handler, command: DND\Domain\Query\GetUsers, bus: query }

  DND\Domain\Query\GetItemCardsForListHandler:
    class: DND\Domain\Query\GetItemCardsForListHandler
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: tactician.handler, command: DND\Domain\Query\GetItemCardsForList, bus: query }

  DND\Domain\Query\GetItemCardHandler:
    class: DND\Domain\Query\GetItemCardHandler
    arguments:
      - '@DND\Domain\ItemCard\ItemCardRepository'
    tags:
      - { name: tactician.handler, command: DND\Domain\Query\GetItemCard, bus: query }

  DND\Domain\Query\GetCharactersByOwnerHandler:
    class: DND\Domain\Query\GetCharactersByOwnerHandler
    arguments:
      - '@DND\Domain\Character\CharacterRepository'
    tags:
      - { name: tactician.handler, command: DND\Domain\Query\GetCharactersByOwner, bus: query }

  DND\Domain\Query\GetCharacterCardHtmlHandler:
    class: DND\Domain\Query\GetCharacterCardHtmlHandler
    arguments:
      - '@DND\Domain\Character\CharacterRepository'
      - '@DND\Domain\CharacterCard\CharacterCardBuilder'
    tags:
      - { name: tactician.handler, command: DND\Domain\Query\GetCharacterCardHtml, bus: query }

  Calendar\Domain\Query\GetCalendarsForUserHandler:
    class: Calendar\Domain\Query\GetCalendarsForUserHandler
    arguments:
      - '@Calendar\Domain\Calendar\CalendarRepository'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Query\GetCalendarsForUser, bus: query }

  Calendar\Domain\Query\GetCalendarHandler:
    class: Calendar\Domain\Query\GetCalendarHandler
    arguments:
      - '@Calendar\Domain\Calendar\CalendarRepository'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Query\GetCalendar, bus: query }

  Calendar\Domain\Query\GetCalendarParticipantsHandler:
    class: Calendar\Domain\Query\GetCalendarParticipantsHandler
    arguments:
      - '@Calendar\Domain\CalendarParticipant\CalendarParticipantRepository'
    tags:
      - { name: tactician.handler, command: Calendar\Domain\Query\GetCalendarParticipants, bus: query }
    