services:
  DND\Domain\User\UserRepository:
    alias: DND\Infrastructure\User\UserRepository

  DND\Domain\ItemCard\ItemCardRepository:
    alias: DND\Infrastructure\ItemCard\ItemCardRepository

  DND\Domain\Character\CharacterRepository:
    alias: DND\Infrastructure\Character\CharacterRepository

  Calendar\Domain\CalendarParticipant\CalendarParticipantRepository:
    alias: Calendar\Infrastructure\CalendarParticipant\CalendarParticipantRepository
