home:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

quill:
    path: /quill
    controller: App\Controller\IndexController::quill
    methods: [ POST ]

cards:
    path: /cards
    controller: App\Controller\CardController::cards
    methods: [ GET ]

card:
    path: /card
    controller: App\Controller\CardController::card
    methods: [ GET ]


login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [ GET, POST ]

logout:
    path: /logout
    methods: [ GET ]

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [ GET, POST ]

register_info:
    path: /register/info
    controller: App\Controller\RegistrationController::registerInfo
    methods: [ GET ]