services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\QueryBus\QueryBus:
        alias: DND\Infrastructure\Tactician\QueryBus

    App\CommandBus\CommandBus:
        alias: DND\Infrastructure\Tactician\CommandBus

    DND\CharacterCard\Builder\AbstractBuilder:
        class: DND\CharacterCard\Builder\AbstractBuilder
        arguments:
            - '@twig'
            - 'public/css/styles.css'

    App\Twig\ProficiencyDot:
        class: App\Twig\ProficiencyDot
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\ValueDecorator:
        class: App\Twig\ValueDecorator
        tags: [ 'twig.extension' ]

    DND\CharacterCard\Builder\SavingThrowsBuilder:
        parent: DND\CharacterCard\Builder\AbstractBuilder

    DND\CharacterCard\Builder\AbilitiesBuilder:
        parent: DND\CharacterCard\Builder\AbstractBuilder

    DND\CharacterCard\CharacterCardDirector:
        class: DND\CharacterCard\CharacterCardDirector
        arguments:
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\AbilitiesBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'

imports:
    - { resource: 'infrastructure/services.yaml' }
    - { resource: 'repositories.yaml' }
    - { resource: 'cli_commands.yaml' }
    - { resource: 'controllers.yaml' }
    - { resource: 'persisters.yaml' }
    - { resource: 'commands.yaml' }
    - { resource: 'queries.yaml' }