services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\QueryBus\QueryBus:
        alias: DND\Infrastructure\Tactician\QueryBus

    App\CommandBus\CommandBus:
        alias: DND\Infrastructure\Tactician\CommandBus

    DND\CharacterCard\Builder\AbstractBuilder:
        class: DND\CharacterCard\Builder\AbstractBuilder
        arguments:
            - '@twig'

    DND\CharacterCard\Builder\SavingThrowsBuilder:
        parent: DND\CharacterCard\Builder\AbstractBuilder

    DND\CharacterCard\CharacterCardDirector:
        class: DND\CharacterCard\CharacterCardDirector
        arguments:
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'
            - '@DND\CharacterCard\Builder\SavingThrowsBuilder'

imports:
    - { resource: 'infrastructure/services.yaml' }
    - { resource: 'repositories.yaml' }
    - { resource: 'cli_commands.yaml' }
    - { resource: 'controllers.yaml' }
    - { resource: 'persisters.yaml' }
    - { resource: 'commands.yaml' }
    - { resource: 'queries.yaml' }