services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\QueryBus\QueryBus:
        alias: DND\Infrastructure\Tactician\QueryBus

    App\CommandBus\CommandBus:
        alias: DND\Infrastructure\Tactician\CommandBus

    App\Twig\ProficiencyDot:
        class: App\Twig\ProficiencyDot
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\ValueDecorator:
        class: App\Twig\ValueDecorator
        tags: [ 'twig.extension' ]

    DND\CharacterCard\CharacterCardBuilder:
        class: DND\CharacterCard\CharacterCardBuilder
        arguments:
            - 'public/css/styles.css'
            - '@twig'

imports:
    - { resource: 'infrastructure/services.yaml' }
    - { resource: 'repositories.yaml' }
    - { resource: 'cli_commands.yaml' }
    - { resource: 'controllers.yaml' }
    - { resource: 'persisters.yaml' }
    - { resource: 'commands.yaml' }
    - { resource: 'queries.yaml' }