services:
    _defaults:
        autowire: false
        autoconfigure: false

    App\QueryBus\QueryBus:
        alias: DND\Infrastructure\Tactician\QueryBus

    App\CommandBus\CommandBus:
        alias: DND\Infrastructure\Tactician\CommandBus

    App\Twig\ProficiencyDot:
        class: App\Twig\ProficiencyDot
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\QuillDeltaParser:
        class: App\Twig\QuillDeltaParser
        arguments:
            - '@twig'
        tags: [ 'twig.extension' ]

    App\Twig\ValueDecorator:
        class: App\Twig\ValueDecorator
        tags: [ 'twig.extension' ]

    App\Twig\UcWords:
        class: App\Twig\UcWords
        tags: [ 'twig.extension' ]

    App\Twig\BackgroundColorCss:
        class: App\Twig\BackgroundColorCss
        arguments:
            - '%character_card_dev_mode%'
        tags: [ 'twig.extension' ]

    App\Twig\ItemCardImage:
        class: App\Twig\ItemCardImage
        arguments:
            - '%item_card_images_directory%'
        tags: [ 'twig.extension' ]

    DND\Domain\CharacterCard\CharacterCardBuilder:
        class: DND\Domain\CharacterCard\CharacterCardBuilder
        arguments:
            - '@twig'

    App\Security\UserProvider:
        class: App\Security\UserProvider
        arguments:
            - '@DND\Domain\User\UserRepository'

imports:
    - { resource: 'infrastructure/services.yaml' }
    - { resource: 'repositories.yaml' }
    - { resource: 'cli_commands.yaml' }
    - { resource: 'controllers.yaml' }
    - { resource: 'persisters.yaml' }
    - { resource: 'commands.yaml' }
    - { resource: 'queries.yaml' }